runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /scripts
  static_dir: scripts
- url: /.*
  script: main.app
  login: required
- url: /UpdateDatabase
  script: main.app
  login: required

libraries:
- name: jinja2
  version: latest
